### ISSUE TITLE
A few suggested updates

### ISSUE THREAD

**Issue by sdorr** [rer145/ta3#32]
--- issues/bugs:  4/16/2020 from Steve O ----------------------

Can you arrange the left column items superiorly to inferiorly by moving "Innominate..." and the two below it to just below "Radius...";  rename "Vertebrae to "Vertebral Column"; rename "Upper Limb" to "Clavicle and Scapula"; rename "Lower Limb" to "Femur"; . 

Program closes before saving any changes in case file, losing all entered data. And naturally, need to prompt to start new case of data already entered; otherwise, all is lost.

WEBSITE LINK: goes to basic github page (https://github.com/rer145/ta3)  but should go to: https://statsmachine.net/software/TA3/.

About Transition Analysis 3: Displays current version information.  But only shows the software version (0.7.0); could also show: Electron 6.1.9 ; win32 6.3.9600 ; R code version (0.43).  AND I need to add in the database version number to the output. 

Can you tell me how I can update the TA3.R file on Github? How do people update it on their computers? Can TA3 update just the R file, or does it have to update everything, and/or the exe too? Can it update just the exe? (I think you told me yes before).

Menu item Window | Zoom does nothing - can remove it.

Thank you!
---

Transition Analysis 3 0.7.0
Electron 6.1.9
win32 6.3.9600
Locale: en-US

**Comment by rer145** [comment]
Hi Steve,

I've broken these down into separate issues to work on, and some are already in the list of issues/fixes.

New issues:
- #33 Reorder/Rename Sections
- #34 Update website link
- #35 Update About screen
- #36 Remove Window -> Zoom menu item

These issues already exist and still need worked on:
- #27 Add file save prompt when user attempts to exit
- #29 Create method of downloading latest R scripts/data

A question for you is: Why do we need to allow people to update ta3.R outside of what the program provides it? Is there a need for them to provide their own custom analysis file? The plan is to allow a download of just the ta3.R file/data rather than a whole new installation file.

**Comment by sdorr** [comment]
(I sent an email but now I saw this)   Thank you for your reply. I am asking about the TA3.R file because I am hoping I can do that somehow in Github. I will be updating and enhancing, and if I can do it myself that saves you from having to do it.  And if I/we can update just the R file, I am hoping that we don't need to update the whole program every time.

  Also, eventually we will add an option for people to specify their own script to be run, and it would be best if they referred to a different R file. So we have the standard way of analyzing (TA3.R), which changes from time to time (important for forensics), and we will eventually allow people (and us on the TA3 team) to do their own things (newThing.R) in analyses. This summer sometime should be fine.

Thank you!

**Comment by rer145** [comment]
Ok. I am working on a way to pull the latest ta3.R file (issue #29), and will let you know when that's ready. I can walk you through the process of doing a pull request in GitHub, which will allow you to update the files and request they be merged into the code base. Email/text me when you want to setup a time for that.

As far as others being allowed to use their own R files, that can be tricky. For one, they will have to pass in arguments in a specific manner and order. They will also be restricted to only using the R version we have bundled in the app, and the packages that were installed on setup. If they need other packages, it won't quite work without a whole new setup potentially.

**Comment by rer145** [comment]
Fixed in release 0.8.0
